#!/usr/bin/env node
/**
 * Massive universe expansion — run: node scripts/seed-massive.mjs
 * Adds characters, episodes, locations, quotes, deaths, events without overwriting hand-tuned files.
 */
import fs from "fs";
import path from "path";

const root = path.join(process.cwd(), "content");

function w(dir, file, obj) {
  const fp = path.join(root, dir, `${file}.json`);
  if (fs.existsSync(fp)) return false;
  fs.mkdirSync(path.dirname(fp), { recursive: true });
  fs.writeFileSync(fp, JSON.stringify(obj, null, 2));
  return true;
}

function char(slug, name, extra = {}) {
  return {
    id: slug,
    type: "character",
    slug,
    title: name,
    name,
    summary:
      extra.summary ??
      `${name} in the Breaking Bad / Better Call Saul universe.`,
    series: extra.series ?? ["breaking-bad"],
    tags: extra.tags ?? [],
    nicknames: extra.nicknames ?? [],
    status: extra.status ?? "unknown",
    occupation: extra.occupation,
    appearsIn: extra.appearsIn ?? extra.series ?? ["breaking-bad"],
    portraitColor: extra.portraitColor ?? "#4a5568",
    relatedIds: extra.relatedIds ?? [],
    relationships: extra.relationships ?? [],
    episodeIds: extra.episodeIds ?? [],
    quoteIds: extra.quoteIds ?? [],
    trivia: extra.trivia ?? [],
    addedAt: "2026-07-14",
    ...extra,
  };
}

let added = 0;
const track = (ok) => {
  if (ok) added++;
};

// ── CHARACTERS ──
const characters = [
  char("todd-alquist", "Todd Alquist", {
    summary: "Vapid, polite sociopath. Walt's cook after Jesse leaves.",
    status: "deceased",
    occupation: "Meth cook / Neo-Nazi associate",
    portraitColor: "#718096",
    tags: ["antagonist", "neo-nazi"],
    relatedIds: [
      "walter-white",
      "jesse-pinkman",
      "jack-welker",
      "lydia-rodarte-quayle",
      "bb-felina",
    ],
    relationships: [
      { targetId: "walter-white", kind: "employee", label: "Employer" },
      { targetId: "jack-welker", kind: "ally", label: "Uncle's gang" },
    ],
    trivia: ["'Sorry for your loss.'", "Kept a tarantula.", "95% purity cook."],
  }),
  char("victor", "Victor", {
    summary: "Gus Fring's loyal enforcer with a box cutter.",
    status: "deceased",
    occupation: "Enforcer / Los Pollos manager",
    portraitColor: "#2d3748",
    tags: ["cartel", "gus-empire"],
    relatedIds: [
      "gustavo-fring",
      "walter-white",
      "jesse-pinkman",
      "bb-box-cutter",
      "superlab",
    ],
    relationships: [
      { targetId: "gustavo-fring", kind: "employee", label: "Boss" },
    ],
  }),
  char("gale-boetticher", "Gale Boetticher", {
    summary:
      "Brilliant chemist, coffee enthusiast, Walt's intended replacement.",
    status: "deceased",
    occupation: "Chemist",
    portraitColor: "#68d391",
    tags: ["chemist"],
    relatedIds: ["walter-white", "gustavo-fring", "jesse-pinkman"],
    relationships: [
      { targetId: "walter-white", kind: "rival", label: "Replacement threat" },
      { targetId: "gustavo-fring", kind: "employer", label: "Employer" },
    ],
    trivia: ["Major Tom karaoke.", "96% purity without Walt."],
  }),
  char("huell-babineaux", "Huell Babineaux", {
    summary: "Saul's bodyguard. 'Reasonably sized' man of few words.",
    status: "alive",
    occupation: "Bodyguard / pickpocket",
    series: ["breaking-bad", "better-call-saul"],
    appearsIn: ["breaking-bad", "better-call-saul"],
    portraitColor: "#744210",
    relatedIds: ["saul-goodman", "walter-white", "kim-wexler"],
    relationships: [
      { targetId: "saul-goodman", kind: "employee", label: "Boss" },
    ],
    trivia: ["It's a big room.", "Laid on money."],
  }),
  char("patrick-kuby", "Patrick Kuby", {
    summary: "Saul's muscle and Huell's partner.",
    status: "alive",
    occupation: "Enforcer",
    series: ["breaking-bad", "better-call-saul"],
    appearsIn: ["breaking-bad", "better-call-saul"],
    portraitColor: "#553c9a",
    relatedIds: ["saul-goodman", "huell-babineaux", "walter-white"],
  }),
  char("walter-jr", "Walter White Jr.", {
    summary: "Walt and Skyler's son. Cerebral palsy. PF Chang's enthusiast.",
    status: "alive",
    nicknames: ["Flynn"],
    occupation: "Student",
    portraitColor: "#4299e1",
    relatedIds: [
      "walter-white",
      "skyler-white",
      "hank-schrader",
      "marie-schrader",
    ],
    relationships: [
      { targetId: "walter-white", kind: "family", label: "Father" },
      { targetId: "skyler-white", kind: "family", label: "Mother" },
    ],
  }),
  char("jane-margolis", "Jane Margolis", {
    summary:
      "Jesse's neighbor and girlfriend. Tattoo artist. Her death breaks Jesse.",
    status: "deceased",
    occupation: "Tattoo artist",
    portraitColor: "#9f7aea",
    tags: ["tragic"],
    relatedIds: ["jesse-pinkman", "andrea-cantillo", "walter-white"],
    relationships: [
      { targetId: "jesse-pinkman", kind: "partner", label: "Boyfriend" },
    ],
  }),
  char("andrea-cantillo", "Andrea Cantillo", {
    summary: "Single mother, Jesse's later girlfriend. Killed by Todd.",
    status: "deceased",
    portraitColor: "#ed8936",
    relatedIds: [
      "jesse-pinkman",
      "todd-alquist",
      "brock-cantillo",
      "jane-margolis",
    ],
    relationships: [
      { targetId: "jesse-pinkman", kind: "partner", label: "Boyfriend" },
      { targetId: "brock-cantillo", kind: "family", label: "Son" },
    ],
  }),
  char("brock-cantillo", "Brock Cantillo", {
    summary: "Andrea's young son. Poisoned with lily of the valley.",
    status: "alive",
    portraitColor: "#48bb78",
    relatedIds: [
      "andrea-cantillo",
      "jesse-pinkman",
      "lily-of-the-valley",
      "walter-white",
    ],
  }),
  char("elliott-schwartz", "Elliott Schwartz", {
    summary:
      "Gray Matter co-founder. Walt's former partner who got rich without him.",
    status: "alive",
    occupation: "CEO Gray Matter Technologies",
    portraitColor: "#3182ce",
    relatedIds: ["walter-white", "gretchen-schwartz", "gray-matter"],
    relationships: [
      { targetId: "gretchen-schwartz", kind: "partner", label: "Spouse" },
      { targetId: "walter-white", kind: "rival", label: "Former partner" },
    ],
  }),
  char("gretchen-schwartz", "Gretchen Schwartz", {
    summary: "Walt's ex-girlfriend and Gray Matter co-founder.",
    status: "alive",
    occupation: "Gray Matter Technologies",
    portraitColor: "#805ad5",
    relatedIds: ["walter-white", "elliott-schwartz", "gray-matter"],
    relationships: [
      { targetId: "walter-white", kind: "rival", label: "Former partner" },
    ],
  }),
  char("francesca-liddell", "Francesca Liddell", {
    summary: "Saul Goodman's long-suffering secretary.",
    status: "alive",
    series: ["breaking-bad", "better-call-saul"],
    appearsIn: ["breaking-bad", "better-call-saul"],
    occupation: "Secretary",
    portraitColor: "#a0aec0",
    relatedIds: ["saul-goodman", "kim-wexler"],
    relationships: [
      { targetId: "saul-goodman", kind: "employee", label: "Boss" },
    ],
  }),
  char("ted-beneke", "Ted Beneke", {
    summary: "Skyler's boss. IRS fraud. Nearly paralyzed by Huell.",
    status: "alive",
    occupation: "Business owner",
    portraitColor: "#ecc94b",
    relatedIds: ["skyler-white", "walter-white", "huell-babineaux"],
  }),
  char("combo", "Combo Ortega", {
    summary: "Jesse's friend and street dealer. Killed by Tomas.",
    status: "deceased",
    portraitColor: "#38a169",
    relatedIds: ["jesse-pinkman", "badger", "skinny-pete"],
    relationships: [
      { targetId: "jesse-pinkman", kind: "friend", label: "Friend" },
    ],
  }),
  char("wendy", "Wendy", {
    summary: "Meth-addicted prostitute. Jesse's occasional acquaintance.",
    status: "alive",
    portraitColor: "#fc8181",
    relatedIds: ["jesse-pinkman", "skinny-pete", "badger"],
  }),
  char("emilio-koyama", "Emilio Koyama", {
    summary:
      "Domingo's cousin. First cook partner attempt. Killed by phosphine gas.",
    status: "deceased",
    portraitColor: "#4a5568",
    relatedIds: ["krazy-8", "jesse-pinkman", "walter-white", "bb-pilot"],
  }),
  char("domingo-molina", "Domingo Molina", {
    summary: "Krazy-8's partner. Becomes DEA informant Krazy-8.",
    status: "deceased",
    nicknames: ["Krazy-8", "Domingo"],
    portraitColor: "#2f855a",
    relatedIds: ["krazy-8", "emilio-koyama", "walter-white", "dea"],
  }),
  char("old-joe", "Old Joe", {
    summary: "Junkyard owner who disposes of the RV magnet-style.",
    status: "alive",
    portraitColor: "#718096",
    relatedIds: ["jesse-pinkman", "walter-white", "rv"],
  }),
  char("declan", "Declan", {
    summary: "Czech Republic distribution partner in Lydia's network.",
    status: "deceased",
    portraitColor: "#2c5282",
    relatedIds: ["lydia-rodarte-quayle", "walter-white", "jack-welker"],
  }),
  char("dennis-markowski", "Dennis Markowski", {
    summary: "Aryan Brotherhood associate at ABQ Correctional.",
    status: "deceased",
    portraitColor: "#1a202c",
    relatedIds: ["jack-welker", "todd-alquist"],
  }),
  char("errol", "Errol", {
    summary: "Gus Fring's henchman at the laundry.",
    status: "deceased",
    portraitColor: "#1a365d",
    relatedIds: ["gustavo-fring", "superlab", "mike-ehrmantraut"],
  }),
  char("lyle", "Lyle", {
    summary: "Los Pollos Hermanos employee. Manager under Gus.",
    status: "alive",
    portraitColor: "#ffd54a",
    relatedIds: ["gustavo-fring", "los-pollos-hermanos"],
    relationships: [
      { targetId: "gustavo-fring", kind: "employee", label: "Boss" },
    ],
  }),
  char("mercedes", "Mercedes", {
    summary: "Salamanca caretaker at Casa Tranquila.",
    status: "alive",
    portraitColor: "#b7791f",
    relatedIds: ["hector-salamanca", "casa-tranquila", "tuco-salamanca"],
  }),
  char("diane-pinkman", "Diane Pinkman", {
    summary: "Jesse's mother. Estranged relationship.",
    status: "alive",
    portraitColor: "#9b2c2c",
    relatedIds: ["jesse-pinkman", "jesse-house"],
    relationships: [
      { targetId: "jesse-pinkman", kind: "family", label: "Son" },
    ],
  }),
  char("brandon-cantillo", "Brandon Cantillo", {
    summary: "Andrea's brother. Tomás's friend.",
    status: "alive",
    portraitColor: "#2b6cb0",
    relatedIds: ["andrea-cantillo", "jesse-pinkman"],
  }),
  char("group-leader", "Group Leader", {
    summary: "Leader of Jesse's NA group. 'Acceptance is key.'",
    status: "alive",
    portraitColor: "#276749",
    relatedIds: ["jesse-pinkman", "jane-margolis"],
  }),
  char("ken-wins", "Ken Wins", {
    summary: "Obnoxious BMW driver Walt destroys in the pilot parking lot.",
    status: "alive",
    portraitColor: "#1a202c",
    relatedIds: ["walter-white", "bb-pilot"],
    trivia: ["Ken Wins vanity plate.", "Walt blows up his car."],
  }),
  char("dr-delcavoli", "Dr. Delcavoli", {
    summary: "Walt's oncologist.",
    status: "alive",
    occupation: "Oncologist",
    portraitColor: "#ffffff",
    relatedIds: ["walter-white", "skyler-white"],
  }),
  char("clarence", "Clarence", {
    summary: "Sandpiper Crossing resident in the class action.",
    status: "alive",
    series: ["better-call-saul"],
    appearsIn: ["better-call-saul"],
    portraitColor: "#cbd5e0",
    relatedIds: ["saul-goodman", "sandpiper", "kim-wexler"],
  }),
  char("rebecca-mcgill", "Rebecca McGill", {
    summary: "Chuck McGill's ex-wife.",
    status: "alive",
    series: ["better-call-saul"],
    appearsIn: ["better-call-saul"],
    portraitColor: "#667eea",
    relatedIds: ["chuck-mcgill", "kim-wexler"],
    relationships: [
      { targetId: "chuck-mcgill", kind: "family", label: "Ex-husband" },
    ],
  }),
  char("ernesto", "Ernesto", {
    summary: "Chuck's caretaker and HHM employee.",
    status: "alive",
    series: ["better-call-saul"],
    appearsIn: ["better-call-saul"],
    portraitColor: "#4a5568",
    relatedIds: ["chuck-mcgill", "howard-hamlin", "hhmm"],
  }),
  char("lalo-lawyer", "David Rymond", {
    summary: "Cartel attorney who visits Jimmy in jail.",
    status: "alive",
    series: ["better-call-saul"],
    appearsIn: ["better-call-saul"],
    portraitColor: "#2d3748",
    relatedIds: ["lalo-salamanca", "saul-goodman", "cartel"],
  }),
  char("marion", "Marion", {
    summary: "Ed the disappearer's wife in Nebraska. Gene's neighbor.",
    status: "alive",
    series: ["better-call-saul"],
    appearsIn: ["better-call-saul"],
    portraitColor: "#975a16",
    relatedIds: ["saul-goodman", "kim-wexler"],
  }),
  char("jeff", "Jeff", {
    summary: "Cab driver who recognizes Gene Takavic in Omaha.",
    status: "alive",
    series: ["better-call-saul"],
    appearsIn: ["better-call-saul"],
    portraitColor: "#2b6cb0",
    relatedIds: ["saul-goodman", "marion"],
  }),
  char("cary", "Cary", {
    summary: "Howard Hamlin's investigator.",
    status: "alive",
    series: ["better-call-saul"],
    appearsIn: ["better-call-saul"],
    portraitColor: "#4a5568",
    relatedIds: ["howard-hamlin", "lalo-salamanca"],
  }),
  char("lalo-guard", "Mateo", {
    summary: "Cartel gunman in Lalo's war with Gus.",
    status: "deceased",
    series: ["better-call-saul"],
    appearsIn: ["better-call-saul"],
    portraitColor: "#742a2a",
    relatedIds: ["lalo-salamanca", "gustavo-fring", "mike-ehrmantraut"],
  }),
  char("holly-white", "Holly White", {
    summary: "Walt and Skyler's infant daughter.",
    status: "alive",
    portraitColor: "#fbb6ce",
    relatedIds: ["walter-white", "skyler-white", "walter-jr", "ozymandias"],
    relationships: [
      { targetId: "walter-white", kind: "family", label: "Father" },
      { targetId: "skyler-white", kind: "family", label: "Mother" },
    ],
  }),
  char("gonzo", "Gonzo", {
    summary: "Tuco's associate. Crushed by falling rock in desert.",
    status: "deceased",
    portraitColor: "#744210",
    relatedIds: ["tuco-salamanca", "desert-spot"],
  }),
  char("no-doze", "No-Doze", {
    summary: "Tuco's crew. Beaten to death by Tuco.",
    status: "deceased",
    portraitColor: "#2d3748",
    relatedIds: ["tuco-salamanca"],
  }),
  char("spooge", "Spooge", {
    summary: "ATM thief Jesse tracks down.",
    status: "deceased",
    portraitColor: "#1a202c",
    relatedIds: ["jesse-pinkman", "wendy"],
  }),
];

for (const c of characters) {
  track(w("characters", c.slug, c));
}

// ── EPISODES ──
const episodes = [
  {
    id: "bb-cat-in-the-bag",
    slug: "bb-cat-in-the-bag",
    title: "Cat's in the Bag...",
    code: "S01E02",
    season: 1,
    episodeNumber: 2,
    synopsis: "Walt and Jesse dispose of Emilio and imprison Krazy-8.",
    series: ["breaking-bad"],
    characterIds: ["walter-white", "jesse-pinkman", "krazy-8"],
    timelineYear: 2008,
    relatedIds: ["walter-white", "krazy-8", "rv"],
    addedAt: "2026-07-14",
  },
  {
    id: "bb-crazy-handful",
    slug: "bb-crazy-handful",
    title: "...And the Bag's in the River",
    code: "S01E03",
    season: 1,
    episodeNumber: 3,
    synopsis: "Walt kills Krazy-8. The cost of the trade weighs on him.",
    series: ["breaking-bad"],
    characterIds: ["walter-white", "jesse-pinkman", "krazy-8"],
    deathIds: [],
    timelineYear: 2008,
    relatedIds: ["walter-white", "krazy-8"],
    addedAt: "2026-07-14",
  },
  {
    id: "bb-four-days-out",
    slug: "bb-four-days-out",
    title: "Four Days Out",
    code: "S02E09",
    season: 2,
    episodeNumber: 9,
    imdbRating: 9.2,
    synopsis:
      "RV breakdown in desert. Walt's hair falls out. Jesse learns chemistry.",
    series: ["breaking-bad"],
    characterIds: ["walter-white", "jesse-pinkman"],
    locationIds: ["desert-spot"],
    timelineYear: 2009,
    relatedIds: ["rv", "desert-spot", "walter-white", "jesse-pinkman"],
    addedAt: "2026-07-14",
  },
  {
    id: "bb-phoenix",
    slug: "bb-phoenix",
    title: "Phoenix",
    code: "S02E12",
    season: 2,
    episodeNumber: 12,
    imdbRating: 9.1,
    synopsis: "Jane dies. Walt watches and does nothing.",
    series: ["breaking-bad"],
    characterIds: ["walter-white", "jesse-pinkman", "jane-margolis"],
    timelineYear: 2009,
    relatedIds: ["jane-margolis", "walter-white", "jesse-pinkman"],
    consequences: ["Jesse's spiral", "Walt's moral point of no return"],
    addedAt: "2026-07-14",
  },
  {
    id: "bb-abq",
    slug: "bb-abq",
    title: "ABQ",
    code: "S02E13",
    season: 2,
    episodeNumber: 13,
    synopsis: "Two planes collide. Pink teddy bear foreshadowing pays off.",
    series: ["breaking-bad"],
    characterIds: ["walter-white", "jesse-pinkman"],
    objectIds: ["pink-teddy-bear"],
    timelineYear: 2009,
    relatedIds: ["pink-teddy-bear", "walter-white"],
    addedAt: "2026-07-14",
  },
  {
    id: "bb-half-measures",
    slug: "bb-half-measures",
    title: "Half Measures",
    code: "S03E12",
    season: 3,
    episodeNumber: 12,
    imdbRating: 9.3,
    synopsis: "Jesse targets dealers who killed Combo. Walt runs them over.",
    series: ["breaking-bad"],
    characterIds: ["walter-white", "jesse-pinkman", "gustavo-fring", "combo"],
    timelineYear: 2009,
    relatedIds: ["combo", "gustavo-fring", "walter-white"],
    addedAt: "2026-07-14",
  },
  {
    id: "bb-full-measure",
    slug: "bb-full-measure",
    title: "Full Measure",
    code: "S03E13",
    season: 3,
    episodeNumber: 13,
    imdbRating: 9.4,
    synopsis: "Walt kills Gale to save Jesse. 'We are done.'",
    series: ["breaking-bad"],
    characterIds: [
      "walter-white",
      "jesse-pinkman",
      "gale-boetticher",
      "gustavo-fring",
    ],
    timelineYear: 2009,
    relatedIds: ["gale-boetticher", "walter-white", "gustavo-fring"],
    addedAt: "2026-07-14",
  },
  {
    id: "bb-say-my-name",
    slug: "bb-say-my-name",
    title: "Say My Name",
    code: "S05E07",
    season: 5,
    episodeNumber: 7,
    imdbRating: 9.5,
    synopsis: "Walt declares he is Heisenberg. Declan eliminated.",
    series: ["breaking-bad"],
    characterIds: [
      "walter-white",
      "jesse-pinkman",
      "mike-ehrmantraut",
      "declan",
    ],
    quoteIds: ["quote-say-my-name"],
    timelineYear: 2010,
    relatedIds: ["quote-say-my-name", "declan", "walter-white"],
    addedAt: "2026-07-14",
  },
  {
    id: "bb-buried",
    slug: "bb-buried",
    title: "Buried",
    code: "S05E10",
    season: 5,
    episodeNumber: 10,
    synopsis: "Walt buries money in the desert. Lydia on the toilet.",
    series: ["breaking-bad"],
    characterIds: ["walter-white", "lydia-rodarte-quayle", "hank-schrader"],
    locationIds: ["desert-spot"],
    timelineYear: 2010,
    relatedIds: ["desert-spot", "walter-white", "lydia-rodarte-quayle"],
    addedAt: "2026-07-14",
  },
  {
    id: "bb-granite-state",
    slug: "bb-granite-state",
    title: "Granite State",
    code: "S05E15",
    season: 5,
    episodeNumber: 15,
    imdbRating: 9.6,
    synopsis: "Ed the disappearer. Walt in New Hampshire cabin.",
    series: ["breaking-bad"],
    characterIds: ["walter-white", "saul-goodman"],
    timelineYear: 2010,
    relatedIds: ["walter-white", "saul-goodman"],
    addedAt: "2026-07-14",
  },
  {
    id: "bcs-uno",
    slug: "bcs-uno",
    title: "Uno",
    code: "S01E01",
    season: 1,
    episodeNumber: 1,
    synopsis: "Jimmy McGill scams the Kettlemans. The birth of Saul.",
    series: ["better-call-saul"],
    characterIds: ["saul-goodman", "kim-wexler", "mike-ehrmantraut"],
    timelineYear: 2002,
    relatedIds: ["saul-goodman", "kim-wexler"],
    addedAt: "2026-07-14",
  },
  {
    id: "bcs-pimento",
    slug: "bcs-pimento",
    title: "Pimento",
    code: "S01E09",
    season: 1,
    episodeNumber: 9,
    imdbRating: 9.2,
    synopsis: "Jimmy and Chuck fallout. Mike's first kill for Nacho.",
    series: ["better-call-saul"],
    characterIds: [
      "saul-goodman",
      "chuck-mcgill",
      "mike-ehrmantraut",
      "nacho-varga",
    ],
    timelineYear: 2002,
    relatedIds: ["chuck-mcgill", "mike-ehrmantraut", "nacho-varga"],
    addedAt: "2026-07-14",
  },
  {
    id: "bcs-klick",
    slug: "bcs-klick",
    title: "Klick",
    code: "S03E10",
    season: 3,
    episodeNumber: 10,
    synopsis: "Chuck's death. Jimmy's 'S'all good, man.'",
    series: ["better-call-saul"],
    characterIds: [
      "saul-goodman",
      "chuck-mcgill",
      "kim-wexler",
      "howard-hamlin",
    ],
    timelineYear: 2003,
    relatedIds: ["chuck-mcgill", "saul-goodman"],
    addedAt: "2026-07-14",
  },
  {
    id: "bcs-plan-and-execution",
    slug: "bcs-plan-and-execution",
    title: "Plan and Execution",
    code: "S06E07",
    season: 6,
    episodeNumber: 7,
    imdbRating: 9.8,
    synopsis: "Howard's death. Lalo in the dark.",
    series: ["better-call-saul"],
    characterIds: [
      "saul-goodman",
      "kim-wexler",
      "howard-hamlin",
      "lalo-salamanca",
    ],
    timelineYear: 2004,
    relatedIds: ["howard-hamlin", "lalo-salamanca", "kim-wexler"],
    addedAt: "2026-07-14",
  },
  {
    id: "bcs-fun-and-games",
    slug: "bcs-fun-and-games",
    title: "Fun and Games",
    code: "S06E08",
    season: 6,
    episodeNumber: 8,
    synopsis: "Kim leaves. Gus kills Lalo.",
    series: ["better-call-saul"],
    characterIds: [
      "saul-goodman",
      "kim-wexler",
      "gustavo-fring",
      "lalo-salamanca",
    ],
    timelineYear: 2004,
    relatedIds: ["lalo-salamanca", "gustavo-fring", "kim-wexler"],
    addedAt: "2026-07-14",
  },
  {
    id: "bcs-saul-gone",
    slug: "bcs-saul-gone",
    title: "Saul Gone",
    code: "S06E13",
    season: 6,
    episodeNumber: 13,
    synopsis: "Gene captured. 86 years. 'It was all good, man.'",
    series: ["better-call-saul"],
    characterIds: ["saul-goodman", "kim-wexler"],
    quoteIds: ["quote-better-call-saul"],
    timelineYear: 2010,
    relatedIds: ["saul-goodman", "quote-better-call-saul"],
    addedAt: "2026-07-14",
  },
];

for (const ep of episodes) {
  track(w("episodes", ep.slug, { type: "episode", ...ep }));
}

// ── LOCATIONS ──
const locations = [
  {
    id: "walt-house",
    type: "location",
    slug: "walt-house",
    title: "White Residence",
    summary: "7421 Negra Arroyo Lane. Where it all began.",
    lat: 35.1107,
    lng: -106.6099,
    address: "3828 Piermont Dr NE, Albuquerque (filming)",
    series: ["breaking-bad"],
    characterIds: ["walter-white", "skyler-white", "walter-jr", "holly-white"],
    episodeIds: ["bb-pilot", "ozymandias"],
    relatedIds: ["walter-white", "skyler-white", "pontiac-aztek"],
    history: [
      "Pool excavation for money burial",
      "Flynn's birthday",
      "Hank's garage investigation",
    ],
    addedAt: "2026-07-14",
  },
  {
    id: "saul-condo",
    type: "location",
    slug: "saul-condo",
    title: "Saul's Condo",
    summary: "Jimmy/Saul's apartment. Kim moves in.",
    lat: 35.0844,
    lng: -106.6504,
    series: ["better-call-saul", "breaking-bad"],
    characterIds: ["saul-goodman", "kim-wexler"],
    relatedIds: ["saul-goodman", "kim-wexler"],
    addedAt: "2026-07-14",
  },
  {
    id: "industrial-laundry",
    type: "location",
    slug: "industrial-laundry",
    title: "Industrial Laundry",
    summary: "Front for Gus's superlab. Lavandería Brillante.",
    lat: 35.058,
    lng: -106.715,
    series: ["breaking-bad"],
    characterIds: ["gustavo-fring", "walter-white", "jesse-pinkman"],
    organizationIds: ["gus-empire"],
    relatedIds: ["superlab", "gustavo-fring"],
    history: ["Tunnel entrance hidden in industrial machines"],
    addedAt: "2026-07-14",
  },
  {
    id: "madrigal-office",
    type: "location",
    slug: "madrigal-office",
    title: "Madrigal Electromotive HQ",
    summary: "German conglomerate front for Gus's operation.",
    lat: 35.089,
    lng: -106.653,
    series: ["breaking-bad"],
    characterIds: ["gustavo-fring", "lydia-rodarte-quayle", "mike-ehrmantraut"],
    relatedIds: ["gus-empire", "lydia-rodarte-quayle"],
    addedAt: "2026-07-14",
  },
  {
    id: "nursing-home",
    type: "location",
    slug: "nursing-home",
    title: "Casa Tranquila",
    summary: "Hector Salamanca's nursing home. The bell.",
    lat: 35.038,
    lng: -106.672,
    series: ["breaking-bad", "better-call-saul"],
    characterIds: ["hector-salamanca", "mercedes"],
    relatedIds: ["hector-salamanca", "casa-tranquila", "objects-hector-bell"],
    addedAt: "2026-07-14",
  },
  {
    id: "neo-nazi-compound",
    type: "location",
    slug: "neo-nazi-compound",
    title: "Neo-Nazi Compound",
    summary: "Jack Welker's compound. Jesse's cage.",
    lat: 35.2,
    lng: -106.8,
    series: ["breaking-bad"],
    characterIds: ["jack-welker", "todd-alquist", "jesse-pinkman"],
    relatedIds: ["jack-welker", "todd-alquist", "jesse-pinkman", "bb-felina"],
    addedAt: "2026-07-14",
  },
  {
    id: "vacuum-shop",
    type: "location",
    slug: "vacuum-shop",
    title: "Ed's Vacuum Shop",
    summary: "Disappearer service. Best vacuum repairs in town.",
    lat: 35.12,
    lng: -106.58,
    series: ["breaking-bad", "better-call-saul"],
    characterIds: ["saul-goodman", "walter-white"],
    relatedIds: ["saul-goodman", "walter-white", "bb-granite-state"],
    addedAt: "2026-07-14",
  },
  {
    id: "omaha-mall",
    type: "location",
    slug: "omaha-mall",
    title: "Omaha Cinnabon",
    summary: "Gene Takavic's exile. Better Call Saul flash-forwards.",
    lat: 41.2565,
    lng: -95.9345,
    series: ["better-call-saul"],
    characterIds: ["saul-goodman"],
    relatedIds: ["saul-goodman", "jeff", "marion"],
    addedAt: "2026-07-14",
  },
  {
    id: "tohajiilee",
    type: "location",
    slug: "tohajiilee",
    title: "To'hajiilee",
    summary: "Navajo reservation. Ozymandias shootout.",
    lat: 34.5199,
    lng: -105.8701,
    series: ["breaking-bad"],
    characterIds: [
      "walter-white",
      "hank-schrader",
      "jesse-pinkman",
      "jack-welker",
    ],
    episodeIds: ["ozymandias"],
    relatedIds: ["ozymandias", "death-hank-schrader", "desert-spot"],
    history: ["Buried money barrels", "Hank's death", "Neo-Nazi ambush"],
    addedAt: "2026-07-14",
  },
  {
    id: "kettelman-house",
    type: "location",
    slug: "kettelman-house",
    title: "Kettelman House",
    summary: "Where the embezzling couple hid in BCS pilot arc.",
    lat: 35.15,
    lng: -106.62,
    series: ["better-call-saul"],
    characterIds: ["saul-goodman"],
    relatedIds: ["saul-goodman", "bcs-uno"],
    addedAt: "2026-07-14",
  },
];

for (const loc of locations) {
  track(w("locations", loc.slug, loc));
}

// ── QUOTES ──
const quotes = [
  {
    id: "quote-i-am-the-danger",
    type: "quote",
    slug: "i-am-the-danger",
    title: "I am the danger",
    text: "I am not in danger, Skyler. I am the danger.",
    speakerId: "walter-white",
    episodeId: "bb-cornered",
    context: "Walt reveals his Heisenberg identity to Skyler.",
    tags: ["iconic", "heisenberg"],
    series: ["breaking-bad"],
    relatedIds: ["walter-white", "skyler-white"],
    addedAt: "2026-07-14",
  },
  {
    id: "quote-tread-lightly",
    type: "quote",
    slug: "tread-lightly",
    title: "Tread lightly",
    text: "If that's true, if you don't know who I am, then maybe your best course would be to tread lightly.",
    speakerId: "walter-white",
    episodeId: "bb-blood-money",
    series: ["breaking-bad"],
    relatedIds: ["walter-white", "hank-schrader"],
    addedAt: "2026-07-14",
  },
  {
    id: "quote-yeah-science",
    type: "quote",
    slug: "yeah-science",
    title: "Yeah, science!",
    text: "Yeah, Mr. White! Yeah, science!",
    speakerId: "jesse-pinkman",
    episodeId: "bb-four-days-out",
    series: ["breaking-bad"],
    relatedIds: ["jesse-pinkman", "walter-white"],
    addedAt: "2026-07-14",
  },
  {
    id: "quote-sall-good-man",
    type: "quote",
    slug: "sall-good-man",
    title: "S'all good, man",
    text: "S'all good, man!",
    speakerId: "saul-goodman",
    episodeId: "bcs-klick",
    series: ["better-call-saul"],
    relatedIds: ["saul-goodman", "chuck-mcgill"],
    addedAt: "2026-07-14",
  },
  {
    id: "quote-i-know-hes-salamanca",
    type: "quote",
    slug: "i-know-hes-salamanca",
    title: "I know he's Salamanca",
    text: "He'll never see it coming.",
    speakerId: "gustavo-fring",
    episodeId: "bcs-fun-and-games",
    series: ["better-call-saul"],
    relatedIds: ["gustavo-fring", "lalo-salamanca"],
    addedAt: "2026-07-14",
  },
  {
    id: "quote-box-cutter",
    type: "quote",
    slug: "box-cutter-speech",
    title: "Box cutter monologue",
    text: "If you try to interfere, this becomes a much simpler matter.",
    speakerId: "gustavo-fring",
    episodeId: "bb-box-cutter",
    series: ["breaking-bad"],
    relatedIds: ["gustavo-fring", "victor", "bb-box-cutter"],
    addedAt: "2026-07-14",
  },
  {
    id: "quote-walt-jr-breakfast",
    type: "quote",
    slug: "walt-jr-breakfast",
    title: "Have an A1 day",
    text: "Have an A1 day!",
    speakerId: "skyler-white",
    episodeId: "bb-gliding-over-all",
    series: ["breaking-bad"],
    relatedIds: ["skyler-white", "a1a-car-wash"],
    addedAt: "2026-07-14",
  },
  {
    id: "quote-jesse-bitch",
    type: "quote",
    slug: "jesse-bitch",
    title: "Bitch!",
    text: "Bitch!",
    speakerId: "jesse-pinkman",
    episodeId: "bb-pilot",
    tags: ["meme"],
    series: ["breaking-bad"],
    relatedIds: ["jesse-pinkman"],
    addedAt: "2026-07-14",
  },
];

for (const q of quotes) {
  track(w("quotes", q.slug, q));
}

// ── DEATHS ──
const deaths = [
  {
    id: "death-jane-margolis",
    type: "death",
    slug: "jane-margolis",
    title: "Death of Jane Margolis",
    victimId: "jane-margolis",
    killerId: "walter-white",
    episodeId: "bb-phoenix",
    method: "Choked on vomit — Walt did not intervene",
    reason: "Prevented Jesse from leaving; protected secret",
    tags: ["tragic", "pivotal"],
    series: ["breaking-bad"],
    relatedIds: [
      "jane-margolis",
      "walter-white",
      "jesse-pinkman",
      "bb-phoenix",
    ],
    addedAt: "2026-07-14",
  },
  {
    id: "death-gale-boetticher",
    type: "death",
    slug: "gale-boetticher",
    title: "Death of Gale Boetticher",
    victimId: "gale-boetticher",
    killerId: "walter-white",
    episodeId: "bb-full-measure",
    method: "Gunshot",
    reason: "Eliminate Walt's replacement to save Jesse",
    series: ["breaking-bad"],
    relatedIds: ["gale-boetticher", "walter-white", "jesse-pinkman"],
    addedAt: "2026-07-14",
  },
  {
    id: "death-victor",
    type: "death",
    slug: "victor",
    title: "Death of Victor",
    victimId: "victor",
    killerId: "gustavo-fring",
    weaponId: "box-cutter",
    episodeId: "bb-box-cutter",
    method: "Box cutter to throat",
    reason: "Message to Walt and Jesse",
    series: ["breaking-bad"],
    relatedIds: ["victor", "gustavo-fring", "bb-box-cutter", "box-cutter"],
    addedAt: "2026-07-14",
  },
  {
    id: "death-andrea-cantillo",
    type: "death",
    slug: "andrea-cantillo",
    title: "Death of Andrea Cantillo",
    victimId: "andrea-cantillo",
    killerId: "todd-alquist",
    episodeId: "bb-felina",
    method: "Gunshot",
    reason: "Leverage over Jesse",
    series: ["breaking-bad"],
    relatedIds: ["andrea-cantillo", "todd-alquist", "jesse-pinkman"],
    addedAt: "2026-07-14",
  },
  {
    id: "death-lalo-salamanca",
    type: "death",
    slug: "lalo-salamanca",
    title: "Death of Lalo Salamanca",
    victimId: "lalo-salamanca",
    killerId: "gustavo-fring",
    episodeId: "bcs-fun-and-games",
    method: "Gunshot",
    series: ["better-call-saul"],
    relatedIds: ["lalo-salamanca", "gustavo-fring", "howard-hamlin"],
    addedAt: "2026-07-14",
  },
  {
    id: "death-howard-hamlin",
    type: "death",
    slug: "howard-hamlin",
    title: "Death of Howard Hamlin",
    victimId: "howard-hamlin",
    killerId: "lalo-salamanca",
    episodeId: "bcs-plan-and-execution",
    method: "Gunshot",
    accidental: true,
    series: ["better-call-saul"],
    relatedIds: [
      "howard-hamlin",
      "lalo-salamanca",
      "kim-wexler",
      "saul-goodman",
    ],
    addedAt: "2026-07-14",
  },
  {
    id: "death-chuck-mcgill",
    type: "death",
    slug: "chuck-mcgill",
    title: "Death of Chuck McGill",
    victimId: "chuck-mcgill",
    episodeId: "bcs-klick",
    method: "Electrical fire / suicide",
    suicide: true,
    series: ["better-call-saul"],
    relatedIds: ["chuck-mcgill", "saul-goodman", "bcs-klick"],
    addedAt: "2026-07-14",
  },
  {
    id: "death-nacho-varga",
    type: "death",
    slug: "nacho-varga",
    title: "Death of Nacho Varga",
    victimId: "nacho-varga",
    episodeId: "bcs-rock-and-hard-place",
    method: "Suicide by cop",
    suicide: true,
    series: ["better-call-saul"],
    relatedIds: ["nacho-varga", "lalo-salamanca", "cartel"],
    addedAt: "2026-07-14",
  },
];

for (const d of deaths) {
  track(w("deaths", d.slug, d));
}

// ── EVENTS ──
const events = [
  {
    id: "event-plane-crash",
    type: "event",
    slug: "plane-crash",
    title: "Wayfarer 515 Collision",
    summary:
      "Mid-air collision over ABQ. 167 deaths. Jane's father air traffic controller.",
    year: 2009,
    series: ["breaking-bad"],
    participantIds: ["walter-white", "jane-margolis"],
    episodeId: "bb-abq",
    relatedIds: ["bb-abq", "pink-teddy-bear", "jane-margolis"],
    addedAt: "2026-07-14",
  },
  {
    id: "event-desert-money-burial",
    type: "event",
    slug: "desert-money-burial",
    title: "Desert Money Burial",
    summary: "Walt buries $80M in barrels in To'hajiilee.",
    year: 2010,
    locationId: "tohajiilee",
    participantIds: ["walter-white", "hank-schrader"],
    episodeId: "bb-buried",
    relatedIds: ["desert-spot", "walter-white", "bb-buried"],
    addedAt: "2026-07-14",
  },
  {
    id: "event-hector-bomb",
    type: "event",
    slug: "hector-bomb",
    title: "Casa Tranquila Bombing",
    summary: "Hector's wheelchair bomb kills Gus and himself.",
    year: 2010,
    locationId: "nursing-home",
    participantIds: ["hector-salamanca", "gustavo-fring", "walter-white"],
    episodeId: "bb-face-off",
    relatedIds: ["hector-salamanca", "gustavo-fring", "death-gus-fring"],
    addedAt: "2026-07-14",
  },
  {
    id: "event-sandpiper-settlement",
    type: "event",
    slug: "sandpiper-settlement",
    title: "Sandpiper Class Action",
    summary: "Elder abuse lawsuit that builds HHM and Davis & Main.",
    year: 2002,
    participantIds: ["saul-goodman", "kim-wexler", "howard-hamlin"],
    relatedIds: ["sandpiper", "hhmm", "davis-main"],
    addedAt: "2026-07-14",
  },
  {
    id: "event-lalo-escape",
    type: "event",
    slug: "lalo-escape",
    title: "Lalo Escapes Custody",
    summary: "Lalo fakes death and returns to Albuquerque.",
    year: 2004,
    series: ["better-call-saul"],
    participantIds: ["lalo-salamanca", "gustavo-fring"],
    relatedIds: ["lalo-salamanca", "gustavo-fring"],
    addedAt: "2026-07-14",
  },
];

for (const ev of events) {
  track(w("events", ev.slug, ev));
}

// ── OBJECTS ──
const objects = [
  {
    id: "lily-plant",
    type: "object",
    slug: "lily-of-the-valley-plant",
    title: "Lily of the Valley Plant",
    summary: "Walt's poison plant used on Brock.",
    meaning: "Hidden threat in suburban backyard",
    series: ["breaking-bad"],
    episodeIds: ["bb-gliding-over-all"],
    relatedIds: ["lily-of-the-valley", "walter-white", "brock-cantillo"],
    addedAt: "2026-07-14",
  },
  {
    id: "m60-machine-gun",
    type: "object",
    slug: "m60-trunk",
    title: "M60 in Trunk",
    summary: "Walt's machine gun purchased from Lawson.",
    series: ["breaking-bad"],
    episodeIds: ["bb-felina"],
    relatedIds: ["weapon-m60", "walter-white", "jack-welker"],
    addedAt: "2026-07-14",
  },
  {
    id: "gps-tracker",
    type: "object",
    slug: "gps-tracker",
    title: "GPS Tracker",
    summary: "Hank uses Walt's GPS to find the buried money.",
    series: ["breaking-bad"],
    episodeIds: ["bb-buried", "ozymandias"],
    relatedIds: ["hank-schrader", "walter-white", "tohajiilee"],
    addedAt: "2026-07-14",
  },
  {
    id: "saul-ring",
    type: "object",
    slug: "saul-ring",
    title: "Saul's Pinky Ring",
    summary: "Kim's gift. Saul wears it in exile.",
    symbolism: "Connection to Kim across time",
    series: ["better-call-saul"],
    relatedIds: ["saul-goodman", "kim-wexler", "bcs-saul-gone"],
    addedAt: "2026-07-14",
  },
  {
    id: "chucks-letter",
    type: "object",
    slug: "chucks-letter",
    title: "Chuck's Letter",
    summary: "Jimmy keeps Chuck's letter. Kim reads it in prison visit.",
    series: ["better-call-saul"],
    relatedIds: ["chuck-mcgill", "saul-goodman", "kim-wexler"],
    addedAt: "2026-07-14",
  },
];

for (const o of objects) {
  track(w("objects", o.slug, o));
}

// ── VEHICLES ──
const vehicles = [
  {
    id: "challenger",
    type: "vehicle",
    slug: "dodge-challenger",
    title: "Dodge Challenger",
    summary: "Walt buys for Walt Jr. 'It's not pink.'",
    ownerId: "walter-jr",
    series: ["breaking-bad"],
    episodeIds: ["bb-cornered"],
    relatedIds: ["walter-jr", "walter-white"],
    addedAt: "2026-07-14",
  },
  {
    id: "mercedes-slr",
    type: "vehicle",
    slug: "mercedes-slr",
    title: "Mercedes SLR McLaren",
    summary: "Saul's dream car briefly.",
    ownerId: "saul-goodman",
    series: ["breaking-bad"],
    relatedIds: ["saul-goodman"],
    addedAt: "2026-07-14",
  },
  {
    id: "van-vamonos",
    type: "vehicle",
    slug: "vamonos-van",
    title: "Vamonos Pest Van",
    summary: "Tented houses hide meth cooks.",
    series: ["breaking-bad"],
    relatedIds: ["vamonos-pest", "walter-white", "todd-alquist"],
    addedAt: "2026-07-14",
  },
];

for (const v of vehicles) {
  track(w("vehicles", v.slug, v));
}

// ── WEAPONS ──
const weapons = [
  {
    id: "revolver-jesse",
    type: "weapon",
    slug: "jesse-revolver",
    title: "Jesse's Revolver",
    summary: "Used in emotional confrontations.",
    series: ["breaking-bad"],
    episodeIds: ["ozymandias"],
    relatedIds: ["jesse-pinkman"],
    addedAt: "2026-07-14",
  },
  {
    id: "hammer-tuco",
    type: "weapon",
    slug: "tuco-hammer",
    title: "Tuco's Hammer",
    summary: "Brutal tool of the Salamanca trade.",
    series: ["breaking-bad"],
    relatedIds: ["tuco-salamanca", "no-doze"],
    addedAt: "2026-07-14",
  },
];

for (const wp of weapons) {
  track(w("weapons", wp.slug, wp));
}

// ── DRUGS ──
const drugs = [
  {
    id: "chili-p",
    type: "drug",
    slug: "chili-p",
    title: "Chili P",
    summary: "Jesse's signature cutting agent. 'It's the bomb, yo.'",
    series: ["breaking-bad"],
    relatedIds: ["jesse-pinkman", "bb-pilot"],
    addedAt: "2026-07-14",
  },
  {
    id: "pseudoephedrine",
    type: "drug",
    slug: "pseudoephedrine",
    title: "Pseudoephedrine",
    summary: "Cold medicine precursor. Smurfs and pharmacies.",
    chemicalNotes: "C10H15NO — precursor to meth via reduction",
    series: ["breaking-bad"],
    relatedIds: ["walter-white", "jesse-pinkman", "blue-meth"],
    addedAt: "2026-07-14",
  },
];

for (const dr of drugs) {
  track(w("drugs", dr.slug, dr));
}

// ── CASES ──
const cases = [
  {
    id: "case-kettlemans",
    type: "case",
    slug: "kettlemans",
    title: "Kettelman Embezzlement",
    summary: "Jimmy's first big con case.",
    clientIds: ["saul-goodman"],
    lawyerIds: ["saul-goodman"],
    outcome: "Resolved with money return",
    series: ["better-call-saul"],
    relatedIds: ["saul-goodman", "bcs-uno"],
    addedAt: "2026-07-14",
  },
  {
    id: "case-hhmm-chuck",
    type: "case",
    slug: "chuck-mcgill-insurance",
    title: "Chuck McGill Insurance Fraud",
    summary: "Jimmy's malpractice hearing against Chuck.",
    clientIds: ["saul-goodman"],
    lawyerIds: ["saul-goodman", "kim-wexler"],
    outcome: "Chuck humiliated",
    series: ["better-call-saul"],
    relatedIds: ["chuck-mcgill", "bcs-chicanery", "quote-chicanery"],
    addedAt: "2026-07-14",
  },
];

for (const c of cases) {
  track(w("cases", c.slug, c));
}

// ── EASTER EGGS ──
const eggs = [
  {
    id: "egg-green-wheels",
    type: "object",
    slug: "green-wheels",
    title: "Green Wheels on Cars",
    summary: "Vince Gilligan's color code — green objects signal change.",
    tags: ["easter-egg", "symbolism"],
    symbolism: "Transformation and corruption",
    series: ["breaking-bad"],
    relatedIds: ["symbol-green", "walter-white"],
    addedAt: "2026-07-14",
  },
  {
    id: "egg-breaking-bad-title",
    type: "object",
    slug: "breaking-bad-title",
    title: "Breaking Bad Title Meaning",
    summary: "Southern phrase for raising hell / going rogue.",
    tags: ["easter-egg"],
    series: ["breaking-bad"],
    relatedIds: ["walter-white"],
    addedAt: "2026-07-14",
  },
  {
    id: "egg-pizza-roof",
    type: "object",
    slug: "pizza-roof",
    title: "Pizza on the Roof",
    summary: "Walt throws pizza on the roof — became real tourist tradition.",
    tags: ["easter-egg", "meme"],
    series: ["breaking-bad"],
    relatedIds: ["walter-white", "walt-house"],
    addedAt: "2026-07-14",
  },
];

for (const e of eggs) {
  track(w("easter-eggs", e.slug, e));
}

console.log(`Seed massive complete: ${added} new entity files written.`);
